### PR TITLE
Fix encoding issues when exporting database

### PR DESCRIPTION
**Pull request by Cellane**
When migrating my Dokku apps from one host to another, I noticed that a database export of my blog did not go as well as I expected. While most of the data got exported and re-imported successfully, all emojis present in the old database got replaced by question marks in the new one.

Upon further investigation, it seems that the issue lied with the `mysql:export` command, not with the `mysql:import` command, as even the generated dump file lacked most of the emojis.

After searching on the Internet a bit, I found [this](https://stackoverflow.com/questions/20216849/mysqldump-with-utf8-can-not-export-the-right-emojis-string) and [this](https://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf) which led me to the fix introduced in the PR. It definitely worked for me, but I don’t know enough to say that this is the correct solution for everyone.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Yeah my concern here is whether this is always safe to do. Can you do some research to see?

**Comment by Cellane** [comment]
Hard to say for sure, but I might have found some not-direct evidence:

- The root issue is known to the [MySQL team](https://bugs.mysql.com/bug.php?id=71746) and was, in fact, fixed in [MySQL 8.x](https://dev.mysql.com/worklog/task/?id=10353) – as in, MySQL 8.x seems to use `utf8mb4` as the default character set for their CLI tools. This, however, only confirms that the change is correct in principle, not that it’s applicable (and safe) for all cases.
- [`utf8mb4` should be fully backwards compatible with `utf8`](https://mathiasbynens.be/notes/mysql-utf8mb4), so even exporting `utf8`-encoded data as `utf8mb4` should not result in any data loss. A problem might happen if one tries to export data encoded in completely different encoding as `utf8mb4`, but at the same time, I suspect that things would break even without the proposed change. To be completely universal, perhaps the encoding used for database export could be configurable via a command-line option? (But do enough people store their data in anything other than UTF-8 to justify this?)

I’ll try to search a bit more on this later but after reading 10+ articles on this matter, my head started hurting a bit 🤣

**Comment by josegonzalez** [comment]
Can this change be applied to mariadb too?

**Comment by Cellane** [comment]
I was thinking of introducing a similar PR to the `dokku-mariadb` repo if this gets merged here, yes.

**Pull request merged**
